### ISSUE TITLE
Add samples of vesc_hw_interface

### ISSUE THREAD

**Issue by ssr-yuki** [sbgisen/vesc#14]
No sample launch file exists in `vesc_hw_interface` package now.

**Comment by yyagin** [comment]
Hello, @ssr-yuki  I want to integrade four vescs using vesc_hw_interface but I don't sure how am i suppose to implement it. Any help will be appreciated.

**Comment by ssr-yuki** [comment]
Hi @yyagin , thank you for your interest.

We use CombinedRobotHW to drive multiple VESCs, without any additional implements on `vesc_hw_interface`. In the framework, we just load multiple `vesc_hw_interface`-s.
Please see https://github.com/ros-controls/ros_control/wiki/Writing-CombinedRobotHW

**Comment by mzahana** [comment]
@ssr-yuki I am trying to use `vesc_hw_interface` ti interface two VESC controllers. Is there an example launch files and yaml files that demonstrated how to do that?

Here is what I did, but I am unable to interface both controllers.
```bash
<launch>

    <arg name="urdf_file" default="$(find amir_robot_description)/urdf/amir.urdf"/>
    <arg name="left_wheel_yaml" default="$(find amir_hardware)/config/left_wheel.yaml"/>
    <arg name="right_wheel_yaml" default="$(find amir_hardware)/config/right_wheel.yaml"/>
    
    <!-- Robot URDF -->
    <param name="robot_description" textfile="$(arg urdf_file)" />

    <!-- Boot hardware interfaces -->
    <node name="left_wheel_vesc" pkg="vesc_hw_interface" type="vesc_hw_interface_node" output="screen">
        <rosparam command="load" file="$(arg left_wheel_yaml)" />
    </node>

    <node name="right_wheel_vesc" pkg="vesc_hw_interface" type="vesc_hw_interface_node" output="screen">
        <rosparam command="load" file="$(arg right_wheel_yaml)" />
    </node>

</launch>
```

Why the above launch file won't work?

Thanks in advance.
