### ISSUE TITLE
Pole pairs in eprm calculations

### ISSUE THREAD

**Issue by JuliusSustarevas** [sbgisen/vesc#18]
Hi, 
I might be miles off here, but I think the getRpm()  and setRpm functions should also take into account pole pairs.     Is this done somewhere else? My empirical test using the velocity interface shows a discrepancy that seems to match the pole pair count.  Am I wrong here

**Comment by ssr-yuki** [comment]
VESC returns velocity information in RPM unit. Thus the discrepancy is not a bug of drivers but one of VESC firmware or its setting, I think.

However, setting motor poles with vesc_tool does not work in my environments. Could you tell me how to measure real RPM in your test?

**Comment by ssr-yuki** [comment]
I completely understand what you say: VESC returns velocity status in ERPM, i.e. mechanical motor velocity [RPM] * the number of motor pole pairs. 

Now I start to work on this issue.

**Comment by JuliusSustarevas** [comment]
Sorry, for no reply!  But yes, thats what I meant, I ended up just adding
this as a param on interface, but vesc must know the pole pairs and maybe
it can be read from the message.

**Comment by ssr-yuki** [comment]
@JuliusSustarevas We have corrected codes for this issue.
Please check if you still have interest. Thank you for your report.
