### ISSUE TITLE
UART communication

### ISSUE THREAD

**Issue by Parker-Bergen** [sbgisen/vesc#38]
## Abstract
UART Communication from computer/microcontroller with ROS to VESC controller

## Purpose
Having UART communication would allow for more microcontroller to connect to the VESC controllers that don't have enough ports or means of USB communication. Many VESC boards have UART and PMM breakouts for more ways to control the motors, however UART would supply more communication that PMM.

**Comment by ssr-yuki** [comment]
Our team does not consider to use UART communication.
I will close this issue later unless you or someone have/has interests in contribution.
