### ISSUE TITLE
Change the algorithm for homing operation.

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/vesc#5]
### 現在の原点復帰動作
- 動き出し始める最小限の電流で電流制御を行い、弱い力で機械的に原点位置にぶつけにいく
- ホールセンサのカウント値が変化しなくなったことを検知して原点位置にぶつかったことを判定して終了する

この原点復帰手順だと以下の課題が発生したため、動作原理を変更する必要が有る
- 原点復帰動作に失敗した際にモータが燃える
~~（原因は不明。おそらく原点位置にぶつかった際のノイズか何かで通信エラーしたものと思われる）~~
※2020/05/14/15:08 追記： 原点復帰動作後にその場で位置制御を行っており、機械的に行けない場所（機械原点よりほんの少し上）に動こうとする力を発生してしまい過負荷状態になっていたようです。
  - ~~VESC本体の設定でタイムアウト処理ができるのが理想だが、これに関する設定はvesc_tool上では見つからなかった~~
  - モータにサーミスタをつける（VESCのTEMP_MOTORピンを使用する）
  - ~~原点復帰動作時のみ、電流制限を厳しくする（効果が有るか不明）~~
- コンディションによって「大きく加速してしまう」/「全く動かない」という状況が発生する
  - 電流のみを制御しているため、摩擦や粘性の状態に大きく依存している
  - 特にモータの回転方向を間違って指定した際、自重が加わって逆方向に加速してしまうため危険な動作をする
    ※2020/05/14/15:08 追記：回転方向を正しく指定していても逆走する現象がたまに発生するようです。原因調査中。

**Comment by nyxrobotics** [comment]
## 案１
1. 最大電流を小さくする
1. Duty比を指定して原点復帰動作を行う（これだと速度フィードバックをしていないので根本的には解決できていない。電圧は最大回転数と比例するので、電流指令時の無制限な加速はなくなる）
1. Duty比が固定の状態で、電流が一定より大きくなったことを検知して原点にぶつかったことを判別する
1. 原点復帰動作を終了し、最大電流を元に戻す

**Comment by nyxrobotics** [comment]
原点復帰位置より少し内側の位置を初期目標位置・可動範囲の終端とすることでモータが燃える問題は解決できそうです

**Comment by ssr-yuki** [comment]
Duty-based calibration had been implemented by #15.
