### ISSUE TITLE
rpm calculation is not correct

### ISSUE THREAD

**Issue by Tacha-S** [sbgisen/vesc#53]
## Abstract

Motor does not rotate at correct speed even though `gear_ratio` and `num_motor_pole_pairs` are set correctly.

**Comment by nyxrobotics** [comment]
- If the input target value is [rad/sec], it should be divided by the gear ratio here. Also, in other calculations, the pulse counts are calculated by multiplying num_motor_pole_pairs by 3.
  - https://github.com/sbgisen/vesc/blob/84100fae35d2c043a783408363d009ad682171c3/vesc_hw_interface/src/vesc_wheel_controller.cpp#L58
  - https://github.com/sbgisen/vesc/blob/84100fae35d2c043a783408363d009ad682171c3/vesc_hw_interface/src/vesc_wheel_controller.cpp#L72
  - https://github.com/sbgisen/vesc/blob/84100fae35d2c043a783408363d009ad682171c3/vesc_hw_interface/src/vesc_wheel_controller.cpp#L96

**Comment by nyxrobotics** [comment]
I haven't tried it, but maybe something like this will fix it.
- ```motor_hall_ppr = 3 * num_motor_pole_pairs_;```
  - I want to try it in a motor with a known number of poles, because I feel it is right to make it 6 instead of 3 here.
- ```target_pulse_ += target_velocity * motor_hall_ppr / (2 * M_PI) / control_rate_ / gear_ratio_;```
- ```velocity_sens_ += this->counterTD(current_pulse, false) * 2.0 * M_PI / motor_hall_ppr * gear_ratio_ * control_rate_;```

**Comment by nyxrobotics** [comment]
- The code below is wrong in the unit of radian.
https://github.com/sbgisen/vesc/blob/84100fae35d2c043a783408363d009ad682171c3/vesc_hw_interface/src/vesc_servo_controller.cpp#L300-L301
- vesc_servo_controller needs an option to switch between revolution or linear

**Comment by nyxrobotics** [comment]
- Reference about nom_motor_pole_pairs
  - https://toshiba.semicon-storage.com/jp/semiconductor/knowledge/e-learning/brushless-motor/chapter2/the-relationship-between-poles-phases-and-slots.html
  - https://www.akm.com/jp/ja/products/hall-sensor/tutorial/ultra-high-sensitivity/

There are three hall-effect-sensor on the stator. One pair of poles on the rotor should trigger 2 counts on the rise and fall in one rotation. 
I think 6 is correct unless vesc divides by half internally.
I would like to name it ```rotor_pole_pairs``` instead of ```motor_pole_pairs```.

**Comment by jsupratman13** [comment]
Ok, so vesc_hw_interface assumes that you are using FOC and hall sensors. Here, vesc_interface's getPosition function returns vesc's tachometer, which is the number of steps the motor has rotated (different from the usual tachometer definition?) as described in 
https://github.com/vedderb/bldc/blob/50e1aee9c929e0e43afbd332e5a9a29df933e795/motor/mcpwm_foc.c#L1298-L1307

Reading the function description (and personally testing), the relation between vesc's tachometer and revolution is probably
```
revolution = vesc tachometer / (number of hall sensors * number of rotor poles)
```
where the `number of hall sensors` is usually 3 and `number of rotor poles` is the number of poles, not pole pairs. Therefore, we can convert revolution to radians (including gear_ratio) with the following:
```
rad = revolution * 2 * pi * gear_ratio
```

**Comment by jsupratman13** [comment]
With that said, I believe @nyxrobotics approach is correct, `motor_hall_ppr = 3 * num_motor_pole_pairs` will fix it (6 if we use number of poles instead of pairs)

**Comment by nyxrobotics** [comment]
```motor_hall_ppr = 3 * num_rotor_poles``` or ```motor_hall_ppr = 6 * num_rotor_pole_pairs```
