### ISSUE TITLE
Fix position_control_sample.launch

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/vesc#67]
## Abstract
Specify PID gain in position_control_sample.launch.

**Comment by jsupratman13** [comment]
Can you elaborate on this a little bit more?

**Comment by nyxrobotics** [comment]
The sample velocity_duty_control_sample.launch has PID gains but position_control_sample.launch doesn't.
Since these are PID-controlled samples, gain adjustment is a must.
It is better to specify gain parameters for position_control_sample.launch.

https://github.com/sbgisen/vesc/blob/3d5e62e736d2c3f92d26e006b3ccf48f5f5c4dc4/vesc_hw_interface/launch/velocity_duty_control_sample.launch#L8-L25

https://github.com/sbgisen/vesc/blob/3d5e62e736d2c3f92d26e006b3ccf48f5f5c4dc4/vesc_hw_interface/launch/position_control_sample.launch#L8-L19

**Comment by jsupratman13** [comment]
Fair enough.
Do you have any recommended values or should we use the default values?
