### ISSUE TITLE
Publishing vesc_msgs::VescStateStamped for vesc_hw_interface node

### ISSUE THREAD

**Issue by David9696** [sbgisen/vesc#75]
Hi,

Thanks for sharing your package.

Is it possible to subscribe the vesc_msgs::VescStateStamped(sensors/core topic) when using the vesc_hw_interface node?

Thanks.

**Comment by jsupratman13** [comment]
We haven't implemented that feature, but I believe it is possible. May I assume that you want to know vesc's status while using hardware interface?

**Comment by David9696** [comment]
Yes, it is good to know the status of vesc while using hardware interface. 

Thanks.

**Comment by jsupratman13** [comment]
I have no problem with having this feature. Our hands are tied at the moment, so it would be great if you could set up a Pull Request.

**Comment by David9696** [comment]
Hi,

Noted. I am not very good in CPP. But I would try my best to work it out. 

Thanks.
