### ISSUE TITLE
Computed velocity and real velocity not matching in velocity continuous mode

### ISSUE THREAD

**Issue by David9696** [sbgisen/vesc#77]
Hi,

I have tested the latest velocity_control_sample.launch file. However, I realized that the computed velocity and real velocity do not matching.

Previously. I was using the vesc package version of [f0d983c].

(https://github.com/sbgisen/vesc/commit/f0d983c0ef787e3cb42fa917bcbfd7a7651f62a0)
[on Dec 14, 2022](https://github.com/sbgisen/vesc/commit/f0d983c0ef787e3cb42fa917bcbfd7a7651f62a0)]

In this version,  the computed velocity and real velocity are matching.

The following parameters are the same for both cases.

      num_rotor_poles_pairs (half for the latest version)
      gear_ratio
      torque_const

May I know what is the problem?

Thanks.

**Comment by Tacha-S** [comment]
Please show me the result of `rosparam get /vesc_hw_interface_node` in both versions.
Also do you know what the measured and actual speed values are? I would appreciate any relationship such as the measured value is greater than the actual speed.

**Comment by David9696** [comment]
I would update the rosparam once I have the access to my setup.

As a quick reply, this is what I have found:

1. The odometry/position estimation is correct.
2. The actual speed is about 2X lesser than the command speed.

Thanks.

**Comment by jsupratman13** [comment]
Sorry, forgot to fix the conversion bug on vesc_hw_interface.cpp
https://github.com/sbgisen/vesc/blob/fb520b663c0c5df1a03cc46ccebb9d08fce110c7/vesc_hw_interface/src/vesc_hw_interface.cpp#L307

should be
```cpp
const double velocity_rpm = values->getVelocityERPM() / static_cast<double>(num_rotor_poles_ / 2);
```

**Comment by jsupratman13** [comment]
@David9696 

I opened PR #78 which should fix the velocity conversion bug. Let us know if this fixes your environment.

**Comment by David9696** [comment]
Hi @jsupratman13 ,

Yes, is working correctly now. Thanks for your great help.
