### ISSUE TITLE
Parameter loading failed

### ISSUE THREAD

**Issue by Tacha-S** [sbgisen/vesc#83]
## Abstract

The `screw_lead` is not necessary except servo.
https://github.com/sbgisen/vesc/blob/0bb026f6c7ff494e4cddaabb07ef80d839b25cb3/vesc_hw_interface/src/vesc_hw_interface.cpp#L59

If we launch a vesc without `screw_lead` parameter, vesc_hw_interface is terminated in the line.

**Comment by jsupratman13** [comment]
Doesn't hardware_info provide default config?

**Comment by Tacha-S** [comment]
I have been searching, but I have not been able to find any references yet.
