### ISSUE TITLE
Question about VESC control inputs

### ISSUE THREAD

**Issue by Scheggetta** [sbgisen/vesc#95]
As far as I can understand, reading the [original code](https://github.com/mit-racecar/vesc) and the CAN communication [docs](https://github.com/vedderb/bldc/blob/master/documentation/comm_can.md) it's possible to set as control inputs the target speed and steering angle.

Is the acceleration control implemented as well? I don't think so, but I'd like confirmation from you. Thank you!

**Comment by jsupratman13** [comment]
To my understanding, we did not implement the acceleration control

**Comment by Scheggetta** [comment]
Thank you!
